apiVersion: apps/v1
kind: Deployment
metadata:
  name: god-docker
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: go-docker
  template:
    metadata:
    labels:
      app: go-docker
    spec:
      containers:
      - name: godocker
        image: oryzasativa29/godocker:latest
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: godocker-service
spec:
  type: Nodeport
  ports:
  - name: http
    port: 9090
    tagetPort: 8081
  selector:
    app: go-docker
